spring.application.name=application-tracker-api

spring.datasource.url=jdbc:postgresql://localhost:5432/application_tracker
spring.datasource.username=postgres
spring.datasource.password=Kiedrich04!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true